

CUDA_VISIBLE_DEVICES=0 python train.py --seed 0 --exp_name 'exp_14' --rl_weight 0.05  --fusion_type 'local_rl' --tag summe_split0 --model summe_head2_layer3 --lr 0.000119 --epochs 200 --dataset summe --reduced_dim 2048 --num_heads 2 --num_layers 3 --split_idx 0 --pt_path 'llama_emb/summe_sum/' 
CUDA_VISIBLE_DEVICES=0 python train.py --seed 0 --exp_name 'exp_14' --rl_weight 0.05  --fusion_type 'local_rl' --tag summe_split1 --model summe_head2_layer3 --lr 0.000119 --epochs 200 --dataset summe --reduced_dim 2048 --num_heads 2 --num_layers 3 --split_idx 1 --pt_path 'llama_emb/summe_sum/' 
CUDA_VISIBLE_DEVICES=0 python train.py --seed 0 --exp_name 'exp_14' --rl_weight 0.05  --fusion_type 'local_rl' --tag summe_split2 --model summe_head2_layer3 --lr 0.000119 --epochs 200 --dataset summe --reduced_dim 2048 --num_heads 2 --num_layers 3 --split_idx 2 --pt_path 'llama_emb/summe_sum/' 
CUDA_VISIBLE_DEVICES=0 python train.py --seed 0 --exp_name 'exp_14' --rl_weight 0.05  --fusion_type 'local_rl' --tag summe_split3 --model summe_head2_layer3 --lr 0.000119 --epochs 200 --dataset summe --reduced_dim 2048 --num_heads 2 --num_layers 3 --split_idx 3 --pt_path 'llama_emb/summe_sum/' 
CUDA_VISIBLE_DEVICES=0 python train.py --seed 0 --exp_name 'exp_14' --rl_weight 0.05  --fusion_type 'local_rl' --tag summe_split4 --model summe_head2_layer3 --lr 0.000119 --epochs 200 --dataset summe --reduced_dim 2048 --num_heads 2 --num_layers 3 --split_idx 4 --pt_path 'llama_emb/summe_sum/' 

CUDA_VISIBLE_DEVICES=0 python train.py --seed 1 --exp_name 'exp_14' --rl_weight 0.05  --fusion_type 'local_rl' --tag summe_split0 --model summe_head2_layer3 --lr 0.000119 --epochs 200 --dataset summe --reduced_dim 2048 --num_heads 2 --num_layers 3 --split_idx 0 --pt_path 'llama_emb/summe_sum/' 
CUDA_VISIBLE_DEVICES=0 python train.py --seed 1 --exp_name 'exp_14' --rl_weight 0.05  --fusion_type 'local_rl' --tag summe_split1 --model summe_head2_layer3 --lr 0.000119 --epochs 200 --dataset summe --reduced_dim 2048 --num_heads 2 --num_layers 3 --split_idx 1 --pt_path 'llama_emb/summe_sum/' 
CUDA_VISIBLE_DEVICES=0 python train.py --seed 1 --exp_name 'exp_14' --rl_weight 0.05  --fusion_type 'local_rl' --tag summe_split2 --model summe_head2_layer3 --lr 0.000119 --epochs 200 --dataset summe --reduced_dim 2048 --num_heads 2 --num_layers 3 --split_idx 2 --pt_path 'llama_emb/summe_sum/' 
CUDA_VISIBLE_DEVICES=0 python train.py --seed 1 --exp_name 'exp_14' --rl_weight 0.05  --fusion_type 'local_rl' --tag summe_split3 --model summe_head2_layer3 --lr 0.000119 --epochs 200 --dataset summe --reduced_dim 2048 --num_heads 2 --num_layers 3 --split_idx 3 --pt_path 'llama_emb/summe_sum/' 
CUDA_VISIBLE_DEVICES=0 python train.py --seed 1 --exp_name 'exp_14' --rl_weight 0.05  --fusion_type 'local_rl' --tag summe_split4 --model summe_head2_layer3 --lr 0.000119 --epochs 200 --dataset summe --reduced_dim 2048 --num_heads 2 --num_layers 3 --split_idx 4 --pt_path 'llama_emb/summe_sum/' 

CUDA_VISIBLE_DEVICES=0 python train.py --seed 2 --exp_name 'exp_14' --rl_weight 0.05  --fusion_type 'local_rl' --tag summe_split0 --model summe_head2_layer3 --lr 0.000119 --epochs 200 --dataset summe --reduced_dim 2048 --num_heads 2 --num_layers 3 --split_idx 0 --pt_path 'llama_emb/summe_sum/' 
CUDA_VISIBLE_DEVICES=0 python train.py --seed 2 --exp_name 'exp_14' --rl_weight 0.05  --fusion_type 'local_rl' --tag summe_split1 --model summe_head2_layer3 --lr 0.000119 --epochs 200 --dataset summe --reduced_dim 2048 --num_heads 2 --num_layers 3 --split_idx 1 --pt_path 'llama_emb/summe_sum/' 
CUDA_VISIBLE_DEVICES=0 python train.py --seed 2 --exp_name 'exp_14' --rl_weight 0.05  --fusion_type 'local_rl' --tag summe_split2 --model summe_head2_layer3 --lr 0.000119 --epochs 200 --dataset summe --reduced_dim 2048 --num_heads 2 --num_layers 3 --split_idx 2 --pt_path 'llama_emb/summe_sum/' 
CUDA_VISIBLE_DEVICES=0 python train.py --seed 2 --exp_name 'exp_14' --rl_weight 0.05  --fusion_type 'local_rl' --tag summe_split3 --model summe_head2_layer3 --lr 0.000119 --epochs 200 --dataset summe --reduced_dim 2048 --num_heads 2 --num_layers 3 --split_idx 3 --pt_path 'llama_emb/summe_sum/' 
CUDA_VISIBLE_DEVICES=0 python train.py --seed 2 --exp_name 'exp_14' --rl_weight 0.05  --fusion_type 'local_rl' --tag summe_split4 --model summe_head2_layer3 --lr 0.000119 --epochs 200 --dataset summe --reduced_dim 2048 --num_heads 2 --num_layers 3 --split_idx 4 --pt_path 'llama_emb/summe_sum/' 

CUDA_VISIBLE_DEVICES=0 python train.py --seed 3 --exp_name 'exp_14' --rl_weight 0.05  --fusion_type 'local_rl' --tag summe_split0 --model summe_head2_layer3 --lr 0.000119 --epochs 200 --dataset summe --reduced_dim 2048 --num_heads 2 --num_layers 3 --split_idx 0 --pt_path 'llama_emb/summe_sum/' 
CUDA_VISIBLE_DEVICES=0 python train.py --seed 3 --exp_name 'exp_14' --rl_weight 0.05  --fusion_type 'local_rl' --tag summe_split1 --model summe_head2_layer3 --lr 0.000119 --epochs 200 --dataset summe --reduced_dim 2048 --num_heads 2 --num_layers 3 --split_idx 1 --pt_path 'llama_emb/summe_sum/' 
CUDA_VISIBLE_DEVICES=0 python train.py --seed 3 --exp_name 'exp_14' --rl_weight 0.05  --fusion_type 'local_rl' --tag summe_split2 --model summe_head2_layer3 --lr 0.000119 --epochs 200 --dataset summe --reduced_dim 2048 --num_heads 2 --num_layers 3 --split_idx 2 --pt_path 'llama_emb/summe_sum/' 
CUDA_VISIBLE_DEVICES=0 python train.py --seed 3 --exp_name 'exp_14' --rl_weight 0.05  --fusion_type 'local_rl' --tag summe_split3 --model summe_head2_layer3 --lr 0.000119 --epochs 200 --dataset summe --reduced_dim 2048 --num_heads 2 --num_layers 3 --split_idx 3 --pt_path 'llama_emb/summe_sum/' 
CUDA_VISIBLE_DEVICES=0 python train.py --seed 3 --exp_name 'exp_14' --rl_weight 0.05  --fusion_type 'local_rl' --tag summe_split4 --model summe_head2_layer3 --lr 0.000119 --epochs 200 --dataset summe --reduced_dim 2048 --num_heads 2 --num_layers 3 --split_idx 4 --pt_path 'llama_emb/summe_sum/' 

CUDA_VISIBLE_DEVICES=0 python train.py --seed 1112 --exp_name 'exp_14' --rl_weight 0.05  --fusion_type 'local_rl' --tag summe_split0 --model summe_head2_layer3 --lr 0.000119 --epochs 200 --dataset summe --reduced_dim 2048 --num_heads 2 --num_layers 3 --split_idx 0 --pt_path 'llama_emb/summe_sum/' 
CUDA_VISIBLE_DEVICES=0 python train.py --seed 1112 --exp_name 'exp_14' --rl_weight 0.05  --fusion_type 'local_rl' --tag summe_split1 --model summe_head2_layer3 --lr 0.000119 --epochs 200 --dataset summe --reduced_dim 2048 --num_heads 2 --num_layers 3 --split_idx 1 --pt_path 'llama_emb/summe_sum/' 
CUDA_VISIBLE_DEVICES=0 python train.py --seed 1112 --exp_name 'exp_14' --rl_weight 0.05  --fusion_type 'local_rl' --tag summe_split2 --model summe_head2_layer3 --lr 0.000119 --epochs 200 --dataset summe --reduced_dim 2048 --num_heads 2 --num_layers 3 --split_idx 2 --pt_path 'llama_emb/summe_sum/' 
CUDA_VISIBLE_DEVICES=0 python train.py --seed 1112 --exp_name 'exp_14' --rl_weight 0.05  --fusion_type 'local_rl' --tag summe_split3 --model summe_head2_layer3 --lr 0.000119 --epochs 200 --dataset summe --reduced_dim 2048 --num_heads 2 --num_layers 3 --split_idx 3 --pt_path 'llama_emb/summe_sum/' 
CUDA_VISIBLE_DEVICES=0 python train.py --seed 1112 --exp_name 'exp_14' --rl_weight 0.05  --fusion_type 'local_rl' --tag summe_split4 --model summe_head2_layer3 --lr 0.000119 --epochs 200 --dataset summe --reduced_dim 2048 --num_heads 2 --num_layers 3 --split_idx 4 --pt_path 'llama_emb/summe_sum/' 

